"""Canonical provisioning and commissioning contracts (R1a).

Fabric describes what a host is and what was commissioned on it. Nexus, Boot,
and every other product decide what to do about it. Nothing in this family
authorizes an installation, an activation, or a role.

See ``docs/provisioning-contracts.md`` for the family reference, the authority
rules, and the feature-to-minimum-Fabric-version matrix.
"""

from azazel_fabric.provisioning_contracts.integrity import (
    ProvisioningIntegrityError,
    assert_content_digest,
    canonical_contract_bytes,
    canonical_contract_json,
    content_digest,
    digest_payload,
)
from azazel_fabric.provisioning_contracts.models import (
    ActivationReceipt,
    Architecture,
    AssetManifest,
    AuditCheckpointProjection,
    CaptureSupport,
    CommissioningRecord,
    CompatibilityManifest,
    FeatureMinimum,
    HardwareInventory,
    InterfaceAssignment,
    InterfaceIdentity,
    InterfaceIdentitySelector,
    InterfaceRole,
    IsolationProperty,
    ModelManifest,
    OperatorConfirmation,
    PlatformIdentity,
    PowerBudget,
    ProductManifest,
    ProposedGenerationDescriptor,
    ResourceProfile,
    SecurityStateProjection,
    StorageDeviceIdentity,
    TestedCompatibilityTuple,
    ThermalBudget,
    TopologyProfile,
)
from azazel_fabric.provisioning_contracts.registry import (
    CAPABILITY_STATES,
    INTERFACE_ROLES,
    REGISTERED_DEPLOYMENT_PROFILES,
    REGISTERED_PRODUCTS,
    is_registered_deployment_profile,
    is_registered_interface_role,
    is_registered_product,
)
from azazel_fabric.provisioning_contracts.validation import (
    BANNED_PROVISIONING_FIELDS,
    BANNED_ROLE_INFERENCE_FIELDS,
    BANNED_TIER_CLAIM_FIELDS,
    COMPOSITE_IDENTITY_FIELDS,
    InterfaceResolutionError,
    assert_no_provisioning_directives,
    assert_no_resource_tier_claim,
    assert_no_role_inference,
    assert_not_expired,
    assert_selector_is_composite,
    contains_provisioning_directive,
    interface_composite_key,
    matching_interfaces,
    resolve_interface_assignment,
)

__all__ = [
    # models
    "ActivationReceipt",
    "Architecture",
    "AssetManifest",
    "AuditCheckpointProjection",
    "CaptureSupport",
    "CommissioningRecord",
    "CompatibilityManifest",
    "FeatureMinimum",
    "HardwareInventory",
    "InterfaceAssignment",
    "InterfaceIdentity",
    "InterfaceIdentitySelector",
    "InterfaceRole",
    "IsolationProperty",
    "ModelManifest",
    "OperatorConfirmation",
    "PlatformIdentity",
    "PowerBudget",
    "ProductManifest",
    "ProposedGenerationDescriptor",
    "ResourceProfile",
    "SecurityStateProjection",
    "StorageDeviceIdentity",
    "TestedCompatibilityTuple",
    "ThermalBudget",
    "TopologyProfile",
    # registries
    "CAPABILITY_STATES",
    "INTERFACE_ROLES",
    "REGISTERED_DEPLOYMENT_PROFILES",
    "REGISTERED_PRODUCTS",
    "is_registered_deployment_profile",
    "is_registered_interface_role",
    "is_registered_product",
    # canonical bytes / digests
    "ProvisioningIntegrityError",
    "assert_content_digest",
    "canonical_contract_bytes",
    "canonical_contract_json",
    "content_digest",
    "digest_payload",
    # validation
    "BANNED_PROVISIONING_FIELDS",
    "BANNED_ROLE_INFERENCE_FIELDS",
    "BANNED_TIER_CLAIM_FIELDS",
    "COMPOSITE_IDENTITY_FIELDS",
    "InterfaceResolutionError",
    "assert_no_provisioning_directives",
    "assert_no_resource_tier_claim",
    "assert_no_role_inference",
    "assert_not_expired",
    "assert_selector_is_composite",
    "contains_provisioning_directive",
    "interface_composite_key",
    "matching_interfaces",
    "resolve_interface_assignment",
]
